@startuml

start
:Disparo;
if (Casilla vacia?) then (yes)
  :Mensaje: Agua;
elseif (Hay barco?) then (yes)
  :Mensaje: Disparo acertado;

  if( Barco hundido?) then (yes)
    :Tocado y hundio;
   else (no)
    :Barco golpeado;
  endif
elseif (Habia disparado antes?) then (yes)
  :Mensaje:Ya habias disparado aqui;
   else (default)

endif
stop
@enduml